import { z } from 'zod';
import { Identifier } from '../identifier.js';
import { ClientMessageSchema } from './client_message.js';
import type { GatewayMessage } from './gateway_message.js';

///////////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////////
//	EnvelopeTypes — the protocol version, and the wrapper every frame travels in
///////////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////////

/**
 * The version of this protocol that these programs speak.
 *
 * Every frame states the version it was written for, and the gateway refuses a version it
 * does not support at the moment a connection authenticates. A peer therefore learns
 * straight away whether it can talk to the other side, instead of discovering it through a
 * validation failure on some later message.
 *
 * Version 2 changed what a language-model stage result carries while a generation is still
 * running: the text produced by that one run, in `newText`, where version 1 carried the whole
 * answer so far in `text`. A gateway of version 1 does not accept a version 2 frame, so a
 * worker built after the change is refused by a gateway built before it at the moment it
 * authenticates, rather than having its first result refused for a shape that gateway's stage
 * payload schema does not allow.
 *
 * Version 3 renamed a set of message types and fields so each states what it identifies —
 * `authenticate`/`authenticated` became `deviceAuthenticate`/`deviceAuthenticated`,
 * `register`/`registered` became `deviceRegister`/`deviceRegistered`, `requestId` became
 * `taskRequestId`, `assignmentId` became `stageAssignmentId`, `principal` became
 * `authIdentity`, `inReplyTo` became `inReplyToMessageId`, and `revision` split into
 * `taskRevision` and `deviceListRevision`. No earlier version is accepted.
 */
export const protocolVersion = 3;

/** The protocol versions the gateway accepts. No earlier version is accepted. */
export const supportedProtocolVersions: number[] = [3];

/**
 * The wrapper around every frame sent in either direction.
 *
 * Nothing in the protocol travels bare. The wrapper carries what a message needs to say
 * about itself and could not say before: which protocol version wrote it, which frame it is,
 * when it was sent, and — on an answer from the gateway — which request it answers.
 */
export const EnvelopeSchema = z.object({
	/** The protocol version this frame was written for. */
	v: z.number().int().positive(),
	/** This frame's own identifier, generated by whoever sent it. */
	id: Identifier,
	/** When this frame was sent, in ISO 8601 format. */
	ts: z.string().datetime(),
	/**
	 * The `id` of the request this frame answers.
	 *
	 * Present on every gateway answer to a client request, and absent on every unsolicited
	 * message the gateway pushes. That is the whole distinction: a push is a frame with no
	 * `inReplyToMessageId`, rather than a message type that happens to have been chosen for pushes.
	 */
	inReplyToMessageId: Identifier.optional(),
});

/** A frame received from a client, once its body has been validated. */
export const ClientEnvelopeSchema = EnvelopeSchema.extend({ body: ClientMessageSchema }).strict();
/** The wrapper a client message travels in. */
export type ClientEnvelope = z.infer<typeof ClientEnvelopeSchema>;

/** A frame sent by the gateway. */
export type GatewayEnvelope = z.infer<typeof EnvelopeSchema> & { body: GatewayMessage };
