import type { EncodedTensor, LlmStagePayload, StagePayload, TaskInput } from './index.js';

///////////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////////
//	StagePayloadFactory — builds the value a pipeline stage starts from
///////////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////////////

/**
 * Builds the `StagePayload` values carried by `stage.assign`/`stage.result` messages, so
 * cli.ts, stage_helper_llm_qwen3_0_6b_sharded.ts, and stage_helper_llm_gemma_nano_chrome_full.ts share one
 * definition of each payload shape instead of repeating the object literals inline.
 */
export class StagePayloadFactory {
	/**
	 * Builds the value handed to the first stage of a task, from the task input the consumer
	 * submitted.
	 *
	 * Every task type is answered here, so the gateway never decides what a first stage
	 * value looks like for itself. Adding a task type is a change to this one method rather
	 * than to each place the gateway starts or restarts a task.
	 *
	 * @param input The task type and value the consumer submitted.
	 * @returns The stage payload to assign to the task's first stage.
	 */
	static initial(input: TaskInput): StagePayload {
		if (input.taskType === 'task_type_dev_formula') return StagePayloadFactory.formula(input.input);
		return StagePayloadFactory.llmPrompt(input.input);
	}

	/**
	 * Builds the payload for a formula stage: the plain number, unchanged.
	 *
	 * @param value The numeric value produced by or fed into a formula stage.
	 * @returns The stage payload to send in a `stage.assign` or `stage.result` message.
	 */
	static formula(value: number): StagePayload {
		return value;
	}

	/**
	 * Builds the initial LLM stage payload for `stage_llm_qwen3_0_6b_shard1of3`'s first round, carrying
	 * the submitted prompt text.
	 *
	 * @param prompt The prompt text submitted for the task.
	 * @returns The stage payload to assign to `stage_llm_qwen3_0_6b_shard1of3`.
	 */
	static llmPrompt(prompt: string): LlmStagePayload {
		return { text: prompt };
	}

	/**
	 * Builds the hand-off payload passed from one shard to the next within the same
	 * generation round: the shard's boundary tensors, plus the token identifiers and
	 * position the receiving shard needs to build its own feeds.
	 *
	 * @param tensors The encoded boundary tensors produced by the shard that just ran.
	 * @param inputIds The token identifiers processed in this round.
	 * @param position The position of the first token in `inputIds` within the full sequence.
	 * @returns The stage payload to assign to the next shard in the round.
	 */
	static llmHandoff(tensors: Record<string, EncodedTensor>, inputIds: number[], position: number): LlmStagePayload {
		return { tensors, inputIds, position };
	}

	/**
	 * Builds the payload the final shard returns to continue generation for another round.
	 *
	 * It carries what this round produced and not the answer so far, so the payload stays the
	 * same size whether it is the first round or the hundredth.
	 *
	 * @param newText The text this round produced, beyond everything the rounds before it produced.
	 * @param nextTokenId The token identifier generated by this round, to feed as the next round's input.
	 * @param position The position `nextTokenId` occupies within the full sequence.
	 * @returns The stage payload that loops back to `stage_llm_qwen3_0_6b_shard1of3`.
	 */
	static llmContinue(newText: string, nextTokenId: number, position: number): LlmStagePayload {
		return { ...StagePayloadFactory.piece(newText), inputIds: [nextTokenId], position, done: false };
	}

	/**
	 * Builds the payload a stage returns to continue a generation it is holding open in the
	 * memory of the device running it.
	 *
	 * The Chrome built-in language-model task uses this when the consumer asked for its answer
	 * in pieces: one stage run reads one piece from a stream the same device keeps open, so the
	 * payload carries that piece and says the generation is already under way.
	 *
	 * @param newText The piece this run read, beyond everything the runs before it read.
	 * @returns The stage payload that runs the same stage again on the same device.
	 */
	static llmPartialText(newText: string): LlmStagePayload {
		return { ...StagePayloadFactory.piece(newText), isContinuation: true, done: false };
	}

	/**
	 * Builds the payload a stage returns once generation is complete.
	 *
	 * This is the one result that carries the whole answer. It is what the gateway stores as
	 * the task result, so a consumer that wants the answer as one piece of text never has to
	 * join anything, and a consumer that has been joining the pieces can check what it built
	 * against what the device that generated it actually produced.
	 *
	 * @param text The complete generated text.
	 * @param newText The text the run that finished the answer produced, when that run produced
	 * any. Left out by a run that produced the whole answer by itself, since there were no
	 * earlier pieces for this to be measured against.
	 * @returns The stage payload that ends the task's generation loop.
	 */
	static llmDone(text: string, newText?: string): LlmStagePayload {
		return { text, ...StagePayloadFactory.piece(newText), done: true };
	}

	/**
	 * States what a run produced, or says nothing when it produced nothing.
	 *
	 * A run that reports an empty piece and a run that reports no piece are saying the same
	 * thing, so only one of the two is ever sent. Every payload builder above goes through this,
	 * which is what saves each of them, and every reader of a payload, from checking for both.
	 *
	 * @param newText The text a run produced, if any.
	 * @returns The piece to spread into a payload, which is nothing at all when there is none.
	 */
	private static piece(newText: string | undefined): { newText?: string } {
		return newText === undefined || newText === '' ? {} : { newText };
	}
}
