import type { EncodedTensor, LlmStagePayload, StagePayload } from "./index.js";

/**
 * Builds the `StagePayload` values carried by `stage.assign`/`stage.result` messages, so
 * cli.ts and stage_llm_helper.ts share one definition of each payload shape instead of
 * repeating the object literals inline.
 */
export class StagePayloadFactory {
	/**
	 * Builds the payload for a formula stage: the plain number, unchanged.
	 *
	 * @param value The numeric value produced by or fed into a formula stage.
	 * @returns The stage payload to send in a `stage.assign` or `stage.result` message.
	 */
	static formula(value: number): StagePayload {
		return value;
	}

	/**
	 * Builds the initial LLM stage payload for `stage_llm_shard1`'s first round, carrying
	 * the submitted prompt text.
	 *
	 * @param prompt The prompt text submitted for the task.
	 * @returns The stage payload to assign to `stage_llm_shard1`.
	 */
	static llmPrompt(prompt: string): LlmStagePayload {
		return { text: prompt };
	}

	/**
	 * Builds the hand-off payload passed from one shard to the next within the same
	 * generation round: the shard's boundary tensors, plus the token identifiers and
	 * position the receiving shard needs to build its own feeds.
	 *
	 * @param tensors The encoded boundary tensors produced by the shard that just ran.
	 * @param inputIds The token identifiers processed in this round.
	 * @param position The position of the first token in `inputIds` within the full sequence.
	 * @returns The stage payload to assign to the next shard in the round.
	 */
	static llmHandoff(tensors: Record<string, EncodedTensor>, inputIds: number[], position: number): LlmStagePayload {
		return { tensors, inputIds, position };
	}

	/**
	 * Builds the payload the final shard returns to continue generation for another round.
	 *
	 * @param text The generated text so far.
	 * @param nextTokenId The token identifier generated by this round, to feed as the next round's input.
	 * @param position The position `nextTokenId` occupies within the full sequence.
	 * @returns The stage payload that loops back to `stage_llm_shard1`.
	 */
	static llmContinue(text: string, nextTokenId: number, position: number): LlmStagePayload {
		return { text, inputIds: [nextTokenId], position, done: false };
	}

	/**
	 * Builds the payload the final shard returns once generation is complete.
	 *
	 * @param text The complete generated text.
	 * @returns The stage payload that ends the task's generation loop.
	 */
	static llmDone(text: string): LlmStagePayload {
		return { text, done: true };
	}
}
